"""计划共创默认节奏；schemas.PlanPrefs 与 cocreate seed 共用。"""

DEFAULT_LEARNING_DURATION = "约 1–2 周"
DEFAULT_PRACTICE_DURATION = "约 4 周"
DEFAULT_APPLICATION_DURATION = "长尾"
DEFAULT_DAILY_MINUTES = 30
DEFAULT_LEARNING_ACTIVITY_MAX = 6
DEFAULT_PRACTICE_ACTIVITY_MAX = 4
DEFAULT_APPLICATION_ACTIVITY_MAX = 3
